import asyncio
import json
from pathlib import Path

import httpx

from app.models.events import StreamEventType, stream_event
from app.models.schemas import AiAppConfig, AppChatStreamRequest, ChatAttachment, ModelConfig, ModelCredential
from app.services.chat_service import ChatService
from app.services.spec_service import SpecKitResult
from app.skills import SkillRegistry
from app.skills.base import SkillSpec
from app.tools import ToolRegistry
from app.tools.weather import WeatherTool
from app.tools.web_search import WebSearchTool


class FakeJeecgClient:
    async def get_model_config(self, model_id, user_context):
        return ModelConfig(
            id=model_id or "model-1",
            model_name="test-model",
            base_url="https://example.com/v1",
        )


class FakeChatService(ChatService):
    async def _stream_complete(self, model, request, messages, use_tools=False):
        yield "reply:"
        yield request.input


def fake_spec_generator(requirement: str) -> SpecKitResult:
    return SpecKitResult(
        spec=f"# Spec\n{requirement}",
        plan="# Plan",
        tasks=["Task 1", "Task 2"],
        note="Generated by fake spec-kit",
        spec_path="/tmp/spec.md",
        plan_path="/tmp/plan.md",
        tasks_path="/tmp/tasks.md",
        feature_dir="/tmp/spec-feature",
        source="spec-kit",
    )


class FakeToolCallingChatService(ChatService):
    async def _stream_complete(self, model, request, messages, use_tools=False):
        if use_tools:
            yield {
                "id": "call-weather-1",
                "type": "function",
                "function": {
                    "name": "weather",
                    "arguments": json.dumps({"city": "广州"}, ensure_ascii=False),
                },
            }
            return
        yield "广州天气已查询完成。"


class FakeWebSearchChatService(ChatService):
    async def _stream_complete(self, model, request, messages, use_tools=False):
        if use_tools:
            yield {
                "id": "call-search-1",
                "type": "function",
                "function": {
                    "name": "web_search",
                    "arguments": json.dumps({"query": "JeecgBoot 最新版本"}, ensure_ascii=False),
                },
            }
            return
        yield "已根据搜索结果总结。"


class FailingJeecgClient:
    async def get_model_config(self, model_id, user_context):
        raise ValueError("请选择 AI 模型")


class UnexpectedJeecgClient:
    async def get_model_config(self, model_id, user_context):
        raise AssertionError("skill validation should run before model config lookup")


def collect_stream(service: ChatService, request: AppChatStreamRequest) -> list[str]:
    async def run():
        return [event async for event in service.stream(request)]

    return asyncio.run(run())


def initial_messages(service: ChatService, request: AppChatStreamRequest) -> list[dict]:
    return asyncio.run(service._initial_messages(request))


def parse_sse(event: str) -> dict:
    data = event.removeprefix("data:").strip()
    return json.loads(data)


def test_stream_event_uses_unified_schema():
    event = parse_sse(
        stream_event(
            "request-1",
            StreamEventType.TOOL_CALL,
            {"toolName": "weather"},
            "conversation-1",
            "topic-1",
        )
    )

    assert event == {
        "event": "TOOL_CALL",
        "requestId": "request-1",
        "conversationId": "conversation-1",
        "topicId": "topic-1",
        "data": {"toolName": "weather"},
    }


def test_chat_stream_success_events():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="你好",
    )

    events = collect_stream(FakeChatService(FakeJeecgClient()), request)
    parsed_events = [parse_sse(event) for event in events]

    assert parsed_events[0]["event"] == "INIT_REQUEST_ID"
    assert parsed_events[1]["event"] == "MESSAGE"
    assert parsed_events[1]["data"]["message"] == "reply:"
    assert parsed_events[2]["event"] == "MESSAGE"
    assert parsed_events[2]["data"]["message"] == "你好"
    assert parsed_events[-1]["event"] == "MESSAGE_END"


def test_initial_messages_include_context_history():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="我刚才选的 skills 有哪些内容？",
        messages=[
            {"role": "user", "content": "我选择了 jeecgboot-uniapp-template skill"},
            {"role": "assistant", "content": "这个 skill 会生成 Spec / Plan / Tasks。"},
        ],
    )

    messages = initial_messages(ChatService(FakeJeecgClient()), request)

    assert messages == [
        {"role": "system", "content": "你是 JeecgBoot AI 应用开发助手。请直接、准确地回答用户问题。"},
        {"role": "user", "content": "我选择了 jeecgboot-uniapp-template skill"},
        {"role": "assistant", "content": "这个 skill 会生成 Spec / Plan / Tasks。"},
        {"role": "user", "content": "我刚才选的 skills 有哪些内容？"},
    ]


def test_initial_messages_send_current_image_attachment_as_vision_input():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="这是一张什么图片？",
        attachments=[
            ChatAttachment(
                id="image-1",
                name="image.png",
                size=12,
                type="image/png",
                url="data:image/png;base64,aW1hZ2U=",
            )
        ],
    )

    messages = initial_messages(ChatService(FakeJeecgClient()), request)
    user_content = messages[-1]["content"]

    assert isinstance(user_content, list)
    assert user_content[0]["type"] == "text"
    assert "这是一张什么图片？" in user_content[0]["text"]
    assert "图片附件已作为视觉输入传给模型" in user_content[0]["text"]
    assert "暂不支持解析" not in user_content[0]["text"]
    assert user_content[1] == {
        "type": "image_url",
        "image_url": {
            "url": "data:image/png;base64,aW1hZ2U=",
            "detail": "auto",
        },
    }
    assert request.attachments[0].extraction_status == "vision_input"


def test_tool_registry_exposes_openai_tools():
    registry = ToolRegistry()
    tools = registry.openai_tools()
    tool_names = [tool["function"]["name"] for tool in tools]

    assert tools[0]["type"] == "function"
    assert "weather" in tool_names
    assert "web_search" in tool_names
    weather_tool = next(tool for tool in tools if tool["function"]["name"] == "weather")
    assert weather_tool["function"]["parameters"]["required"] == ["city"]


def test_skill_registry_lists_builtin_skills():
    skills = SkillRegistry().list_skills()

    assert {skill.id for skill in skills} >= {"jeecgboot-dev", "jeecgboot-uniapp-template"}
    uniapp = SkillRegistry().get("jeecgboot-uniapp-template")
    assert uniapp.selection_mode == "single"
    assert uniapp.available_tool_names == ["weather"]
    assert uniapp.forbidden_tool_names == ["weather"]
    assert uniapp.spec_kit.enabled is True
    assert "不要重新搭建框架" in uniapp.instruction
    assert "不重新创建工程" in (uniapp.spec_kit.instruction or "")
    assert "uniapp_page" in uniapp.templates
    assert uniapp.package_path


def test_skill_registry_loads_skill_package_directories(tmp_path: Path):
    skill_dir = tmp_path / "custom-skill"
    template_dir = skill_dir / "templates"
    template_dir.mkdir(parents=True)
    (skill_dir / "instructions.md").write_text("自定义指令正文", encoding="utf-8")
    (template_dir / "spec-kit.md").write_text("自定义 spec-kit 指令", encoding="utf-8")
    (template_dir / "spec.md").write_text("# Spec Template", encoding="utf-8")
    (skill_dir / "skill.yaml").write_text(
        """
name: 自定义 Skill
description: 自定义描述
instruction_file: instructions.md
category: 测试
selection_mode: multiple
spec_kit:
  enabled: true
  mode: suggest
  instruction_file: templates/spec-kit.md
templates:
  spec: templates/spec.md
tags:
  - test
""",
        encoding="utf-8",
    )

    skill = SkillRegistry(tmp_path).get("custom-skill")

    assert skill.id == "custom-skill"
    assert skill.name == "自定义 Skill"
    assert skill.instruction == "自定义指令正文"
    assert skill.default_tool_names == []
    assert skill.spec_kit.enabled is True
    assert skill.spec_kit.instruction == "自定义 spec-kit 指令"
    assert skill.templates["spec"].endswith("templates/spec.md")


def test_chat_stream_selected_skill_event_and_prompt():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="开发一个小程序页面",
        skill_ids=["jeecgboot-uniapp-template"],
    )
    service = FakeChatService(FakeJeecgClient(), spec_generator=fake_spec_generator)

    events = collect_stream(service, request)
    parsed_events = [parse_sse(event) for event in events]
    messages = initial_messages(service, request)

    assert parsed_events[1]["event"] == "SKILL_SELECTED"
    assert parsed_events[1]["data"]["skillId"] == "jeecgboot-uniapp-template"
    assert parsed_events[2]["event"] == "SPEC_EVENT"
    assert parsed_events[2]["data"]["stage"] == "start"
    assert parsed_events[2]["data"]["template"] == "jeecgboot-uniapp-template"
    assert parsed_events[3]["data"]["stage"] == "spec"
    assert parsed_events[3]["data"]["artifact"]["path"] == "/tmp/spec.md"
    assert parsed_events[4]["data"]["stage"] == "plan"
    assert parsed_events[5]["data"]["stage"] == "tasks"
    assert parsed_events[6]["data"]["stage"] == "completed"
    assert parsed_events[6]["data"]["result"]["taskCount"] == 2
    assert parsed_events[7]["event"] == "MESSAGE"
    assert "JeecgBoot UniApp 模板开发" in messages[0]["content"]
    assert "不要重新搭建框架" in messages[0]["content"]
    assert "spec-kit 绑定策略" in messages[0]["content"]
    assert "jeecgboot-uniapp-template" in messages[0]["content"]


def test_skill_limits_available_tools():
    service = ChatService(FakeJeecgClient())

    assert service._available_tool_names(None) == ["weather"]
    assert service._available_tool_names(None, enable_search=True) == ["weather", "web_search"]
    assert service._available_tool_names(["jeecgboot-dev"]) == ["weather"]
    assert service._available_tool_names(["jeecgboot-dev"], enable_search=True) == ["weather", "web_search"]
    assert service._available_tool_names(["jeecgboot-uniapp-template"]) == []
    assert service._available_tool_names(["jeecgboot-uniapp-template"], enable_search=True) == []


def test_model_request_filters_tools_by_skill():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="开发一个小程序页面",
        skill_ids=["jeecgboot-uniapp-template"],
    )
    service = ChatService(FakeJeecgClient())
    model = ModelConfig(
        id="model-1",
        model_name="test-model",
        base_url="https://example.com/v1",
        credential=ModelCredential(api_key="test-key"),
    )

    payload, *_ = service._build_model_request(
        model,
        request,
        stream=True,
        messages=initial_messages(service, request),
        use_tools=True,
    )

    assert "tools" not in payload


def test_model_request_exposes_web_search_only_when_enabled():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="查询 JeecgBoot 最新版本",
        enable_search=True,
    )
    service = ChatService(FakeJeecgClient())
    model = ModelConfig(
        id="model-1",
        model_name="test-model",
        base_url="https://example.com/v1",
        credential=ModelCredential(api_key="test-key"),
    )

    payload, *_ = service._build_model_request(
        model,
        request,
        stream=True,
        messages=initial_messages(service, request),
        use_tools=True,
    )
    tool_names = [tool["function"]["name"] for tool in payload["tools"]]

    assert "web_search" in tool_names
    assert "extra_body" not in payload
    assert "联网搜索已开启" in initial_messages(service, request)[0]["content"]


def test_chat_stream_error_event():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev"),
        input="你好",
    )

    events = collect_stream(ChatService(FailingJeecgClient()), request)
    parsed_events = [parse_sse(event) for event in events]

    assert parsed_events[0]["event"] == "INIT_REQUEST_ID"
    assert parsed_events[-1]["event"] == "ERROR"
    assert "请选择 AI 模型" in parsed_events[-1]["data"]["message"]


def test_unknown_skill_returns_structured_error_before_model_lookup():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="你好",
        skill_ids=["missing-skill"],
    )

    events = collect_stream(ChatService(UnexpectedJeecgClient()), request)
    parsed_events = [parse_sse(event) for event in events]

    assert [event["event"] for event in parsed_events] == ["INIT_REQUEST_ID", "ERROR"]
    assert parsed_events[-1]["data"]["code"] == "SKILL_NOT_FOUND"
    assert parsed_events[-1]["data"]["skillIds"] == ["missing-skill"]
    assert "Skill 不存在或未注册" in parsed_events[-1]["data"]["message"]


def test_conflicting_single_skill_returns_structured_error():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="开发一个页面",
        skill_ids=["jeecgboot-dev", "jeecgboot-uniapp-template"],
    )

    events = collect_stream(ChatService(UnexpectedJeecgClient()), request)
    parsed_events = [parse_sse(event) for event in events]

    assert [event["event"] for event in parsed_events] == ["INIT_REQUEST_ID", "ERROR"]
    assert parsed_events[-1]["data"]["code"] == "SKILL_CONFLICT"
    assert parsed_events[-1]["data"]["skillIds"] == ["jeecgboot-dev", "jeecgboot-uniapp-template"]
    assert "互斥" in parsed_events[-1]["data"]["message"]


def test_skill_missing_tool_dependency_returns_structured_error():
    registry = SkillRegistry()
    registry._skills["broken-skill"] = SkillSpec(
        id="broken-skill",
        name="Broken Skill",
        description="测试缺失工具依赖",
        instruction="测试",
        default_tool_names=["missing-tool"],
    )
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev", model_id="model-1"),
        input="你好",
        skill_ids=["broken-skill"],
    )

    events = collect_stream(ChatService(UnexpectedJeecgClient(), skill_registry=registry), request)
    parsed_events = [parse_sse(event) for event in events]

    assert [event["event"] for event in parsed_events] == ["INIT_REQUEST_ID", "ERROR"]
    assert parsed_events[-1]["data"]["code"] == "SKILL_TOOL_UNAVAILABLE"
    assert parsed_events[-1]["data"]["skillIds"] == ["broken-skill"]
    assert parsed_events[-1]["data"]["toolNames"] == ["missing-tool"]


def test_weather_tool_stream_events():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev"),
        input="广州天气怎么样",
    )

    requested_paths = []

    def handler(request: httpx.Request) -> httpx.Response:
        requested_paths.append(request.url.path)
        if request.url.path == "/v7/weather/3d":
            return httpx.Response(
                200,
                json={
                    "code": "200",
                    "updateTime": "2026-06-01T11:00+08:00",
                    "fxLink": "https://www.qweather.com/weather/guangzhou-101280101.html",
                    "daily": [
                        {
                            "fxDate": "2026-06-01",
                            "sunrise": "05:41",
                            "sunset": "19:08",
                            "tempMax": "31",
                            "tempMin": "24",
                            "textDay": "多云",
                            "textNight": "阴",
                            "iconDay": "101",
                            "iconNight": "104",
                            "windDirDay": "东南风",
                            "windScaleDay": "3",
                            "windDirNight": "南风",
                            "windScaleNight": "2",
                            "humidity": "72",
                            "precip": "0.0",
                            "pressure": "1004",
                            "uvIndex": "8",
                        },
                        {
                            "fxDate": "2026-06-02",
                            "tempMax": "32",
                            "tempMin": "25",
                            "textDay": "小雨",
                            "textNight": "小雨",
                            "iconDay": "305",
                            "iconNight": "305",
                            "windDirDay": "南风",
                            "windScaleDay": "3",
                            "humidity": "80",
                        },
                    ],
                },
            )
        return httpx.Response(404)

    registry = ToolRegistry()
    registry._tools["weather"] = WeatherTool(
        api_host="https://test.qweather.example",
        geo_api_host="https://test-geo.qweather.example",
        api_key="test-key",
        transport=httpx.MockTransport(handler),
    )

    events = collect_stream(FakeToolCallingChatService(FakeJeecgClient(), registry), request)
    parsed_events = [parse_sse(event) for event in events]

    assert [event["event"] for event in parsed_events] == [
        "INIT_REQUEST_ID",
        "TOOL_CALL",
        "TOOL_RESULT",
        "MESSAGE",
        "MESSAGE_END",
    ]
    assert parsed_events[1]["data"]["toolName"] == "weather"
    assert parsed_events[1]["data"]["input"] == {"city": "广州"}
    assert parsed_events[2]["data"]["result"]["city"] == "广州"
    assert parsed_events[2]["data"]["result"]["source"] == "QWeather"
    assert parsed_events[2]["data"]["result"]["high"] == "31°C"
    assert parsed_events[2]["data"]["result"]["low"] == "24°C"
    assert parsed_events[2]["data"]["result"]["iconDay"] == "101"
    assert parsed_events[2]["data"]["result"]["daily"][0]["weather"] == "多云转阴"
    assert "广州天气" in parsed_events[3]["data"]["message"]
    assert "/geo/v2/city/lookup" not in requested_paths


def test_model_tool_call_delta_is_merged():
    service = ChatService(FakeJeecgClient())
    pending = {}

    for payload in [
        {
            "index": 0,
            "id": "call-1",
            "function": {"name": "weather", "arguments": '{"city"'},
        },
        {
            "index": 0,
            "function": {"arguments": ': "广州"}'},
        },
    ]:
        service._merge_tool_call_delta(pending, payload)

    tool_calls = service._finalize_tool_calls(pending)
    tool, tool_input = service._resolve_tool_call(tool_calls[0])

    assert tool.spec.name == "weather"
    assert tool_input == {"city": "广州"}


def test_weather_tool_geo_404_has_actionable_error():
    async def run_tool() -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(404, request=request)

        tool = WeatherTool(
            api_host="https://test.qweather.example",
            geo_api_host="https://test-geo.qweather.example",
            api_key="test-key",
            transport=httpx.MockTransport(handler),
        )
        await tool.run({"city": "不存在城市"})

    try:
        asyncio.run(run_tool())
    except ValueError as exc:
        message = str(exc)
    else:
        raise AssertionError("expected ValueError")

    assert "QWEATHER_GEO_API_HOST" in message
    assert "API Host" in message


def test_weather_tool_missing_key_returns_error_event():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev"),
        input="广州天气怎么样",
    )

    registry = ToolRegistry()
    registry._tools["weather"] = WeatherTool(api_host="", geo_api_host="", api_key="")

    events = collect_stream(FakeToolCallingChatService(FakeJeecgClient(), registry), request)
    parsed_events = [parse_sse(event) for event in events]

    assert parsed_events[0]["event"] == "INIT_REQUEST_ID"
    assert parsed_events[1]["event"] == "TOOL_CALL"
    assert parsed_events[-1]["event"] == "ERROR"
    assert "QWEATHER_API_HOST" in parsed_events[-1]["data"]["message"] or "QWEATHER_API_KEY" in parsed_events[-1]["data"]["message"]


def test_web_search_tool_stream_events():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev"),
        input="JeecgBoot 最新版本是什么",
        enable_search=True,
    )

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/html/"
        return httpx.Response(
            200,
            text="""
            <html><body>
              <a rel="nofollow" class="result__a" href="https://www.jeecg.com">JeecgBoot 官网</a>
              <a class="result__snippet">JeecgBoot 低代码开发平台。</a>
            </body></html>
            """,
        )

    registry = ToolRegistry()
    registry._tools["web_search"] = WebSearchTool(transport=httpx.MockTransport(handler))

    events = collect_stream(FakeWebSearchChatService(FakeJeecgClient(), registry), request)
    parsed_events = [parse_sse(event) for event in events]

    assert [event["event"] for event in parsed_events] == [
        "INIT_REQUEST_ID",
        "TOOL_CALL",
        "TOOL_RESULT",
        "MESSAGE",
        "MESSAGE_END",
    ]
    assert parsed_events[1]["data"]["toolName"] == "web_search"
    assert parsed_events[2]["data"]["result"]["query"] == "JeecgBoot 最新版本"
    assert parsed_events[2]["data"]["result"]["results"][0]["url"] == "https://www.jeecg.com"
    assert "搜索结果" in parsed_events[3]["data"]["message"]


def test_web_search_tool_unwraps_duckduckgo_redirect_url():
    request = AppChatStreamRequest(
        app=AiAppConfig(id="ai-sdk-dev"),
        input="OpenAI Codex",
        enable_search=True,
    )

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            text="""
            <html><body>
              <a rel="nofollow" class="result__a" href="/l/?uddg=https%3A%2F%2Fopenai.com%2Fcodex">OpenAI Codex</a>
              <a class="result__snippet">OpenAI Codex product page.</a>
            </body></html>
            """,
        )

    registry = ToolRegistry()
    registry._tools["web_search"] = WebSearchTool(transport=httpx.MockTransport(handler))

    events = collect_stream(FakeWebSearchChatService(FakeJeecgClient(), registry), request)
    parsed_events = [parse_sse(event) for event in events]

    assert parsed_events[2]["data"]["result"]["results"][0]["url"] == "https://openai.com/codex"


def test_model_non_json_response_has_actionable_error():
    response = httpx.Response(
        200,
        content=b"<html>not json</html>",
        headers={"content-type": "text/html"},
        request=httpx.Request("POST", "https://example.com/v1/chat/completions"),
    )
    service = ChatService(FakeJeecgClient())

    try:
        service._parse_model_response(response, "https://example.com/v1/chat/completions")
    except ValueError as exc:
        message = str(exc)
    else:
        raise AssertionError("expected ValueError")

    assert "模型接口返回非 JSON 响应" in message
    assert "https://example.com/v1/chat/completions" in message
    assert "text/html" in message


def test_model_empty_response_has_actionable_error():
    response = httpx.Response(
        200,
        content=b"",
        request=httpx.Request("POST", "https://example.com/v1/chat/completions"),
    )
    service = ChatService(FakeJeecgClient())

    try:
        service._parse_model_response(response, "https://example.com/v1/chat/completions")
    except ValueError as exc:
        message = str(exc)
    else:
        raise AssertionError("expected ValueError")

    assert "模型接口返回空响应" in message


def test_chat_completions_endpoint_adds_v1_for_bare_host():
    service = ChatService(FakeJeecgClient())

    assert service._chat_completions_endpoint("https://sub.umboe.com") == "https://sub.umboe.com/v1/chat/completions"


def test_chat_completions_endpoint_keeps_versioned_base():
    service = ChatService(FakeJeecgClient())

    assert service._chat_completions_endpoint("https://sub.umboe.com/v1") == "https://sub.umboe.com/v1/chat/completions"


def test_chat_completions_endpoint_keeps_full_endpoint():
    service = ChatService(FakeJeecgClient())

    assert (
        service._chat_completions_endpoint("https://sub.umboe.com/v1/chat/completions")
        == "https://sub.umboe.com/v1/chat/completions"
    )
